---
# tasks file for openstack

- name: "Be sure that necessary variables are set"
  set_fact:
   os_auth:
    auth_url: "{{ os['auth_url'] }}"
    username: "{{ os['username'] }}"
    password: "{{ os['password'] }}"
    user_domain_name: "{{ os['user_domain_name'] }}"    
    project_name: "{{ os['project_name'] }}"    
    project_id: "{{ os['project_id'] }}"
  tags: openstack

- name: "Be sure to have created the virtual machine BOOT volume"
  os_volume:
   state: "present"
   auth: "{{ os_auth }}"
   size: "{{ item['boot_volume']['size'] }}"
   image: "{{ item['boot_volume']['image'] }}"
   display_name: "{{ item['boot_volume']['name'] }}"
   display_description: "Boot Volume used by {{ item['fqdn'] }}"
  with_items: 
   - "{{ os_vms }}"
  when:
   - item['state'] is defined
   - item['state'] == "present"
   - item['fqdn'] is defined
   - item['fqdn'] != ""
   - item['boot_volume'] is defined
   - item['boot_volume'] is defined
   - item['boot_volume']['name'] is defined
   - item['boot_volume']['name'] != ""
   - item['boot_volume']['size'] is defined
   - item['boot_volume']['size'] != ""
   - item['boot_volume']['image'] is defined
   - item['boot_volume']['image'] != ""
  tags: openstack

- name: "Be sure to have created the virtual machine DATA volume"
  os_volume:
   state: "present"
   auth: "{{ os_auth }}"
   size: "{{ item['data_volume']['size'] }}"
   display_name: "{{ item['data_volume']['name'] }}"
   display_description: "Data Volume used by {{ item['fqdn'] }}"
  with_items: 
   - "{{ os_vms }}"
  when:
   - item['state'] is defined
   - item['state'] == "present"
   - item['fqdn'] is defined
   - item['fqdn'] != ""
   - item['data_volume'] is defined
   - item['data_volume'] != ""
   - item['data_volume']['name'] is defined
   - item['data_volume']['name'] != ""
   - item['data_volume']['size'] is defined
   - item['data_volume']['size'] != ""
  tags: openstack

- name: "Be sure to have set fixed IP on the IdP"
  os_port:
   state: "present"
   auth: "{{ os_auth }}"
   name: "{{ item['port_name'] }}"
   network: "{{ os['network']}}"
   fixed_ips:
    - ip_address: "{{ item['ip_priv'] }}"
  with_items: "{{ os_vms }}"
  when:
   - item['state'] is defined
   - item['state'] == "present"
   - item['port_name'] is defined
   - item['port_name'] != ""
   - item['ip_priv'] is defined
   - item['ip_priv'] != ""
  tags: openstack

- name: "Be sure to have created the new instance with persistent + additional volume"
  os_server:
   state: "present"
   auth: "{{ os_auth }}"
   name: "{{ item['fqdn'] }}"
   boot_volume: "{{ item['boot_volume']['name'] }}"
   flavor: "{{ item['flavor'] }}"
   nics:
    - port-name: "{{ item['port_name'] }}"
   timeout: "{{ os['timeout'] }}"
   security_groups: "{{ item['security_groups'] }}"
   floating_ips: "{{ item['ip_pub'] }}"
   key_name: "{{ item['key_name'] }}"
   volumes: "{{ item['data_volume']['name'] }}"
  with_items: "{{ os_vms }}"
  register: os_srv
  when:
   - item['state'] is defined
   - item['state'] == "present"
   - item['fqdn'] is defined
   - item['fqdn'] != ""
   - item['flavor'] is defined
   - item['flavor'] != ""
   - item['port_name'] is defined
   - item['port_name'] != ""
   - item['ip_pub'] is defined
   - item['ip_pub'] != ""
   - item['key_name'] is defined
   - item['key_name'] != ""
   - item['boot_volume'] is defined
   - item['boot_volume'] != ""
   - item['boot_volume']['name'] is defined
   - item['boot_volume']['name'] != ""
   - item['data_volume'] is defined
   - item['data_volume'] != ""
   - item['data_volume']['name'] is defined
   - item['data_volume']['name'] != ""
  tags: openstack

- name: "Be sure to have created the new instance with persistent without additional volume"
  os_server:
   state: "present"
   auth: "{{ os_auth }}"
   name: "{{ item['fqdn'] }}"
   boot_volume: "{{ item['boot_volume']['name'] }}"
   flavor: "{{ item['flavor'] }}"
   nics:
    - port-name: "{{ item['port_name'] }}"
   timeout: "{{ os['timeout'] }}"
   security_groups: "{{ item['security_groups'] }}"
   floating_ips: "{{ item['ip_pub'] }}"
   key_name: "{{ item['key_name'] }}"
  with_items: "{{ os_vms }}"
  register: os_srv
  when:
   - item['state'] is defined
   - item['state'] == "present"
   - item['fqdn'] is defined
   - item['fqdn'] != ""
   - item['flavor'] is defined
   - item['flavor'] != ""
   - item['port_name'] is defined
   - item['port_name'] != ""
   - item['ip_pub'] is defined
   - item['ip_pub'] != ""
   - item['key_name'] is defined
   - item['key_name'] != ""
   - item['boot_volume'] is defined
   - item['boot_volume'] != ""
   - item['boot_volume']['name'] is defined
   - item['boot_volume']['name'] != ""
  tags: openstack

- name: "Be sure to have deleted the new instance"
  os_server:
   state: "absent"
   auth: "{{ os_auth }}"
   name: "{{ item['fqdn'] }}"
  with_items: "{{ os_vms }}"
  when:
   - item['state'] is defined
   - item['state'] == "absent"
   - item['fqdn'] is defined
   - item['fqdn'] != ""
  tags: openstack

- name: "Be sure to have removed fixed IP on the IdP"
  os_port:
   state: "absent"
   auth: "{{ os_auth }}"
   name: "{{ item['port_name'] }}"
   network: "{{ os['network']}}"
   fixed_ips:
    - ip_address: "{{ item['ip_priv'] }}"
  with_items: "{{ os_vms }}"
  when:
   - item['state'] is defined
   - item['state'] == "absent"
   - item['port_name'] is defined
   - item['port_name'] != ""
   - item['ip_priv'] is defined
   - item['ip_priv'] != ""
  tags: openstack

- name: "Be sure to have deleted the virtual machine DATA volumes"
  os_volume:
   state: "absent"
   auth: "{{ os_auth }}"
   display_name: "{{ item['data_volume']['name'] }}"
  with_items: 
   - "{{ os_vms }}"
  when:
   - item['state'] is defined
   - item['state'] == "absent"
   - item['data_volume'] is defined
   - item['data_volume'] != ""
   - item['data_volume']['name'] is defined
   - item['data_volume']['name'] != ""
  tags: openstack

- name: "Be sure to have deleted the virtual machine BOOT volume"
  os_volume:
   state: "absent"
   auth: "{{ os_auth }}"
   display_name: "{{ item['boot_volume']['name'] }}"
  with_items: 
   - "{{ os_vms }}"
  when:
   - item['state'] is defined
   - item['state'] == "absent"
   - item['boot_volume'] is defined
   - item['boot_volume'] != ""
   - item['boot_volume']['name'] is defined
   - item['boot_volume']['name'] != ""
  tags: openstack
