---
# tasks file for openstack

- name: "Be sure that necessary variables are set"
  set_fact:
   os_auth:
    auth_url: "{{ os['auth_url'] }}"
    username: "{{ os['username'] }}"
    password: "{{ os['password'] }}"
    user_domain_name: "{{ os['user_domain_name'] }}"    
    project_name: "{{ os['project_name'] }}"    
    project_id: "{{ os['project_id'] }}"
  tags: 
   - openstack
   - os-create
   - os-delete

- name: "Create OpenStack Instances"
  include_tasks: create-os-vms.yml
  with_items: "{{ os_vms }}"
  when:
   - item['state'] is defined
   - item['state'] == "present"
  tags: 
   - openstack
   - os-create

- name: "Delete OpenStack Instances"
  include_tasks: delete-os-vms.yml
  with_items: "{{ os_vms }}"
  when:
   - item['state'] is defined
   - item['state'] == "absent"
  tags: 
   - openstack
   - os-delete
